### ISSUE TITLE
Criar CRUD de categorias

### ISSUE THREAD

**Issue by quaresmateo** [quaresmateo/unity-game-api#27]
A tabela de `category_game` tem somente um campo chamado `category_name`

![image](https://user-images.githubusercontent.com/26655732/97064735-836db600-157e-11eb-85ea-4d176c219324.png)

**Comment by wandersonpsantos** [comment]
Tem os campos que o crud de categorias deve ter?

**Comment by wandersonpsantos** [comment]
tem me marcar nessa issue?

**Comment by quaresmateo** [comment]
Posso sim, vou só detalhar o que deve ser feito na descrição

**Comment by quaresmateo** [comment]
@wandersonpsantos se estiveres participando do hackotuberfest, cria apenas a [migration](https://adonisjs.com/docs/4.1/migrations) que eu vou marcar como `hacktoberfest-accepted`.

**Comment by wandersonpsantos** [comment]
é pro hacktoberfest mesmo, mais ja terminei =D
